### ISSUE TITLE
Login via github gives error 500

### ISSUE THREAD

**Issue by codingthat** [openfl/www.openfl.org#86]
![openfl-github-500-error](https://user-images.githubusercontent.com/26723818/33242210-87f876bc-d2d1-11e7-8b4d-59cc0f7c26e6.gif)

(I was already logged into github, btw.  And Google and Twitter logins do work: they instead bring me to an app authorization page.)

Chromium Version 62.0.3202.89 (Official Build) Built on Ubuntu , running on LinuxMint 18.1 (64-bit)
http://community.openfl.org/t/what-is-the-fastest-per-pixel-manipulation-in-html5/1352/6

**Comment by joshtynjala** [comment]
Seems to be working now. Closing.
